# Generated by Django 6.0.5 on 2026-05-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardgame",
            name="name_eng",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="영어 이름"
            ),
        ),
    ]
