# Generated by Django 6.0.5 on 2026-05-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0002_boardgame_name_eng"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardgame",
            name="description",
            field=models.JSONField(
                blank=True, max_length=200, verbose_name="게임 소개"
            ),
        ),
        migrations.AlterField(
            model_name="crimescene",
            name="description",
            field=models.JSONField(
                blank=True, max_length=200, verbose_name="게임 소개"
            ),
        ),
        migrations.AlterField(
            model_name="escape",
            name="description",
            field=models.JSONField(
                blank=True, max_length=200, verbose_name="게임 소개"
            ),
        ),
    ]
