# Generated by Django 6.0.5 on 2026-05-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0003_alter_boardgame_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boardgame",
            name="mechanism",
        ),
        migrations.RemoveField(
            model_name="boardgame",
            name="reviews",
        ),
        migrations.RemoveField(
            model_name="crimescene",
            name="reviews",
        ),
        migrations.RemoveField(
            model_name="escape",
            name="reviews",
        ),
    ]
