# Generated by Django 6.0.5 on 2026-05-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "contents",
            "0004_remove_boardgame_mechanism_remove_boardgame_reviews_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boardgame",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="crimescene",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="escape",
            name="image_url",
        ),
        migrations.AlterField(
            model_name="boardgame",
            name="description",
            field=models.TextField(blank=True, verbose_name="게임 설명"),
        ),
        migrations.AlterField(
            model_name="crimescene",
            name="description",
            field=models.TextField(blank=True, verbose_name="게임 설명"),
        ),
        migrations.AlterField(
            model_name="escape",
            name="description",
            field=models.TextField(blank=True, verbose_name="게임 설명"),
        ),
    ]
